Fixed issue #3 and #4
oversight/httpprobe pull request #5
Opened 2022-04-13 12:44 UTC by AnjaBruls

This resolves issue #3 and #4.

2022-04-19 07:28 UTC, joente commented on httpprobe.py
> +    cl.setup_logger(args.log_level, args.log_colorized)
This is not correct, `setup_logger` must be initialized using `AgentCoreClient.`, before the init

2022-04-19 07:29 UTC, joente requested changes
setup logger must be changed

2022-04-19 08:18 UTC, AnjaBruls commented on httpprobe.py
> +    cl.setup_logger(args.log_level, args.log_colorized)
Fixed in [a79a237](https://github.com/oversight/httpprobe/pull/5/commits/a79a2379811dfe0d6e04c88de6b8a4f95a05a999)

2022-05-12 14:03 UTC, joente approved these changes

2022-05-12 14:03 UTC, merged